##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Sat Mar 01 15:26:31 ICT 2025]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32f401rct6
BOARD = board/stm32f401rct6

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
board/stm32f401rct6/Core/Src/gpio.c \
board/stm32f401rct6/Core/Src/adc.c \
board/stm32f401rct6/Core/Src/dma.c \
board/stm32f401rct6/Core/Src/tim.c \
board/stm32f401rct6/Core/Src/stm32f4xx_it.c \
board/stm32f401rct6/Core/Src/stm32f4xx_hal_msp.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.c \
board/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c \
board/stm32f401rct6/Core/Src/system_stm32f4xx.c \
board/stm32f401rct6/Core/Src/sysmem.c \
board/stm32f401rct6/Core/Src/syscalls.c  

C_SOURCES +=  \
board/stm32f401rct6/Core/Extension/lcd.c \
board/stm32f401rct6/Core/Extension/pwm.c \
board/stm32f401rct6/Core/Extension/adc_hardware.c \
board/stm32f401rct6/Core/Extension/board.c 
C_SOURCES +=  \
app/main.c 
# ASM sources
ASM_SOURCES =  \
startup_stm32f401xc.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32F401xC


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Iboard/stm32f401rct6/Core/Inc \
-Iboard/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Inc \
-Iboard/stm32f401rct6/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-Iboard/stm32f401rct6/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
-Iboard/stm32f401rct6/Drivers/CMSIS/Include
C_INCLUDES +=  \
-Iboard/stm32f401rct6/Core/Extension 
C_INCLUDES +=  \
-Iapp

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F401RCTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***